### ISSUE TITLE
Fix Interpolation

### ISSUE THREAD

**Issue by Elsaam2y** [JonnyBurger/remotion-2-0-trailer#1]
Hi, 

thanks for this new tutorial and for this amazing work. While working on this one, I came across an error in `src/Interpolate.tsx`. I think you may need to make the following change in line 26: `<div style={{ fontSize: 35 }}>for n{'>'}2 points</div>`. Otherwise, the character ">"  won't be valid inside a JSX element. If I missed something, please let me know. 

Thanks again.

**Comment by JonnyBurger** [comment]
Thanks a lot! Updated!
